
# console.log config
spring.output.ansi.enabled=ALWAYS

#spring config port number
server.port=9090
#enable logging of the api classes
logging.level.com.task=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR

#Circuit breaker
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false

#circuit breaker defaults
resilience4j.circuitbreaker.metrics.enabled=true
resilience4j.circuitbreaker.metrics.legacy.enabled=true
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=6
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=15s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10


#circuit breaker retry config
resilience4j.retry.metrics.enabled=true
resilience4j.retry.metrics.legacy.enabled=true
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=3s
resilience4j.retry.configs.default.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.configs.default.retryExceptions[1]=java.lang.RuntimeException

#ServicePlan Circuit Breaker policy should use default config
resilience4j.circuitbreaker.instances.servicePlan.baseConfig=default

#ServicePlan retry policy should use default config
resilience4j.retry.instances.servicePlan.baseConfig=default